name: decentralized-inference

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - openpyxl
  - tensorboard
  - pip
  - pip:
      - --index-url https://download.pytorch.org/whl/cu128
      - torch>=2.7
